version: "3.8"
services:
  lan-to-wg:
    image: linuxserver/wireguard
    container_name: lan-to-wg
    networks:
      docker_bridge_net:
        ipv4_address: ${DOCKER_BRIDGE_IP}
      host_lan_net:
        ipv4_address: ${HOST_LAN_IP}
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./wg0.conf:/config/wg_confs/wg0.conf:ro
      - /lib/modules:/lib/modules:ro
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    env_file:
      - .env
    restart: unless-stopped
networks:
  docker_bridge_net:
    driver: bridge
    ipam:
      config:
        - subnet: ${DOCKER_BRIDGE_SUBNET}
  host_lan_net:
    driver: macvlan
    driver_opts:
      parent: ${HOST_LAN_INTERFACE}
    ipam:
      config:
        - subnet: ${HOST_LAN_SUBNET}
